### ISSUE TITLE
Not Abel to crack some tokens, were as other cracker can crack the token. 

### ISSUE THREAD

**Issue by Mr007jd** [aress31/jwtcat#1]
crackjwt.py script ==> can crack any token.

Note Secret Key is: 1234567890 

$ python3 jwtcat.py -t "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzb21lIjoicGF5bG9hZCJ9.Fw4maeqOtL8pPwiI2_VzYBo4JQ91P1Ow3X3hNqx2wPg" -v -w ~/passwords_long.txt

**Comment by aress31** [comment]
@Mr007jd, could you please provide more information about the decrypted token:

- the header
- the payload

It seems that your private key does not work:
![image](https://user-images.githubusercontent.com/11601622/82375883-2bec7c80-9a19-11ea-8604-ea20639ba527.png)

**Comment by aress31** [comment]
Should be fixed with https://github.com/aress31/jwtcat/pull/19.
