### ISSUE TITLE
help

### ISSUE THREAD

**Issue by suleshy** [aress31/jwtcat#16]
python3 jwtcat.py vulnerable "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJkYXRhIjoie1widXNlcm5hbWVcIjpcInRlc3RcIixcInJvbGVcIjpcInVzZXJcIn0ifQ.XSPy0jZd8CEtHl2e3C1SjPaewco1tjO3iajbkJy2OFQ"

python3 jwtcat.py vulnerable "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJkYXRhIjoie1widXNlcm5hbWVcIjpcInRlc3RcIixcInJvbGVcIjpcInVzZXJcIn0ifQ.XSPy0jZd8CEtHl2e3C1SjPaewco1tjO3iajbkJy2OFQ"

jwtcat.py: error: argument --potfile-path: can't open 'jwtpot.potfile': [Errno 13] Permission denied: 'jwtpot.potfile'

**Comment by xrzhev** [comment]
This error will occur if the current directory does not have write permission when the command is executed.
You should execute the command in a directory where the user executing the command has write access, or execute it with `sudo`.

**Comment by diof-eng** [comment]
Thanks
